#!/bin/bash

DOCKER_USER=g0194776

dep ensure -v
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o lxcfs-admission-webhook
docker build --no-cache -t ${DOCKER_USER}/lxcfs-admission-webhook:latest .
rm -rf lxcfs-admission-webhook

docker push ${DOCKER_USER}/lxcfs-admission-webhook:latest
